/**
 * FixIntegration.ts — Direction AV, V3756-V3765 (Batch 3/3 收口)
 * Plot Hole Auto-Fixer: 集成 + 收口
 */

export class FixPipeline { steps: string[] = ['detect', 'categorize', 'prioritize', 'fix', 'review']; isComplete(step: string): boolean { return this.steps[this.steps.length - 1] === step; } next(step: string): string { const i = this.steps.indexOf(step); return i >= 0 && i < this.steps.length - 1 ? this.steps[i + 1] : 'done'; } }
export class FixWorkflow { states: string[] = ['idle', 'detecting', 'fixing', 'reviewing', 'done']; current = 'idle'; transition(next: string): void { this.current = next; } isComplete(): boolean { return this.current === 'done'; } }
export class AutoFixDirector { decide(holeCount: number, severity: number): string { if (holeCount === 0) return 'done'; if (severity > 0.7) return 'fix_critical'; return 'fix_normal'; } }
export class FixReportGenerator { generate(text: string, holes: number, fixes: number): string { return `文本长度 ${text.length}, 检测到 ${holes} 个漏洞, 应用 ${fixes} 个修复`; } hasReport(text: string): boolean { return text.includes('漏洞'); } }
export class FixVerification { verify(before: string, after: string): { improved: boolean; changeRatio: number } { const ratio = before.length === 0 ? 0 : (after.length - before.length) / before.length; return { improved: ratio > 0, changeRatio: ratio }; } isImproved(result: { improved: boolean }): boolean { return result.improved; } }
export class FixMemoryBank { private _fixes = new Map<string, string>(); store(hole: string, fix: string): void { this._fixes.set(hole, fix); } retrieve(hole: string): string | null { return this._fixes.get(hole) || null; } size(): number { return this._fixes.size; } }
export class FixStats { private _applied = 0; private _verified = 0; recordApplied(): void { this._applied += 1; } recordVerified(): void { this._verified += 1; } getApplied(): number { return this._applied; } getVerified(): number { return this._verified; } verificationRate(): number { return this._applied === 0 ? 0 : this._verified / this._applied; } }
export class FixADirector { decideNextStep(state: { pipelineStep: string; reviewedCount: number; totalCount: number }): string { if (state.pipelineStep === 'done') return 'finalize'; if (state.reviewedCount < state.totalCount) return 'review_more'; return 'apply_more'; } }
export class FixTools { tools: string[] = ['AutoFix', 'ManualEdit', 'Hybrid']; isAvailable(tool: string): boolean { return this.tools.includes(tool); } count(): number { return this.tools.length; } }
export class FixMasterIndex { list(): string[] { return ['HoleAutoDetector', 'HoleCategorizer', 'HolePriorityRanker', 'AutoFixSuggester', 'FixConfidenceScorer', 'ManualReviewQueue', 'FixAttemptTracker', 'DiffVisualizer', 'HoleLinkageDetector', 'MotivationInserter', 'LogicalChainBuilder', 'ContinuityRestorer', 'SettingEnforcer', 'UnexplainedResolver', 'BulkFixApplier', 'FixSafetyChecker', 'RevisionRecorder', 'FixIterationCounter', 'FixPipeline', 'FixWorkflow', 'AutoFixDirector', 'FixReportGenerator', 'FixVerification', 'FixMemoryBank', 'FixStats', 'FixADirector', 'FixTools', 'FixMasterIndex']; } count(): number { return this.list().length; } }
export const AV_BATCH_3_ENGINES = { FixPipeline, FixWorkflow, AutoFixDirector, FixReportGenerator, FixVerification, FixMemoryBank, FixStats, FixADirector, FixTools, FixMasterIndex } as const;