/**
 * TranslationIntegration.ts — Direction AU, V3726-V3735 (Batch 3/3 收口)
 * Translation-Aware Writing: 集成 + 收口
 */

export class TranslationGuide { tips: string[] = ['避免成语', '避免文化引用', '保持简单句', '避免双关', '提供脚注']; randomTip(): string { return this.tips[Math.floor(Math.random() * this.tips.length)]; } isValid(t: string): boolean { return this.tips.includes(t); } }
export class WritingForTranslation { check(text: string): { score: number; issues: string[] } { const issues: string[] = []; if (/说曹操/.test(text)) issues.push('idiom'); if (/饺子/.test(text)) issues.push('cultural'); return { score: Math.max(0, 1 - issues.length * 0.3), issues }; } isGood(check: { score: number }): boolean { return check.score >= 0.7; } }
export class LocaleSpecificTerms { en: string = ''; ja: string = ''; ko: string = ''; isUniversal(): boolean { return this.en === this.ja && this.ja === this.ko; } }
export class TranslationIssuesTracker { private _issues: string[] = []; track(issue: string): void { this._issues.push(issue); } getAll(): string[] { return [...this._issues]; } count(): number { return this._issues.length; } }
export class StylePreservation { original: string = ''; translated: string = ''; isPreserved(): boolean { return this.original.length > 0 && this.translated.length > 0; } similarity(): number { return this.original === this.translated ? 1 : 0.5; } }
export class TranslationFeedbackLoop { private _feedback: { chapter: number; rating: number }[] = []; addFeedback(chapter: number, rating: number): void { this._feedback.push({ chapter, rating }); } averageRating(): number { if (this._feedback.length === 0) return 0; return this._feedback.reduce((s, f) => s + f.rating, 0) / this._feedback.length; } isGood(): boolean { return this.averageRating() >= 4; } }
export class CrossLangIndex { entries = new Map<string, Record<string, string>>(); add(term: string, translations: Record<string, string>): void { this.entries.set(term, translations); } get(term: string, lang: string): string | null { return this.entries.get(term)?.[lang] || null; } size(): number { return this.entries.size; } }
export class TranslationADirector2 { decideAction(quality: number): string { if (quality < 0.5) return 'redo'; if (quality < 0.8) return 'improve'; return 'publish'; } }
export class TranslationTools { tools: string[] = ['DeepL', 'Google Translate', 'ChatGPT', '专业译者']; isAvailable(tool: string): boolean { return this.tools.includes(tool); } count(): number { return this.tools.length; } }
export class TranslationMasterIndex { list(): string[] { return ['CulturalReferenceDetector', 'IdiomaticExpressionDetector', 'WordplayDetector', 'NameAdaptabilityChecker', 'CulturalSensitivityScanner', 'HonorificTracker', 'TranslationLengthEstimator', 'LocaleAdaptability', 'SlangDetector', 'MultilingualCoherence', 'TranslationGlossary', 'ParallelTextGenerator', 'TranslatorNotes', 'LanguagePair', 'TranslationProject', 'TMEntry', 'TranslationMemory', 'TranslationADirector', 'TranslationGuide', 'WritingForTranslation', 'LocaleSpecificTerms', 'TranslationIssuesTracker', 'StylePreservation', 'TranslationFeedbackLoop', 'CrossLangIndex', 'TranslationADirector2', 'TranslationTools', 'TranslationMasterIndex']; } count(): number { return this.list().length; } }
export const AU_BATCH_3_ENGINES = { TranslationGuide, WritingForTranslation, LocaleSpecificTerms, TranslationIssuesTracker, StylePreservation, TranslationFeedbackLoop, CrossLangIndex, TranslationADirector2, TranslationTools, TranslationMasterIndex } as const;