/**
 * ShortStoryIntegration.ts — Direction BH, V4116-V4125 (Batch 3/3 收口)
 * Short Story Adapter: 集成 + 收口
 */

export class ShortStoryPipeline { steps: string[] = ['condense', 'theme', 'pacing', 'ending', 'review']; isComplete(step: string): boolean { return this.steps[this.steps.length - 1] === step; } next(step: string): string { const i = this.steps.indexOf(step); return i >= 0 && i < this.steps.length - 1 ? this.steps[i + 1] : 'done'; } }
export class ShortStoryDirector { decide(state: { wordCount: number; target: number }): string { if (state.wordCount < state.target / 2) return 'expand'; if (state.wordCount > state.target * 1.2) return 'condense'; return 'finalize'; } }
export class ShortStoryReport { generate(stats: { words: number; themes: number; characters: number }): string { return `${stats.words} 字, ${stats.themes} 主题, ${stats.characters} 人物`; } hasReport(s: string): boolean { return s.includes('字'); } }
export class ShortStoryLibrary { private _stories = new Map<string, unknown>(); save(key: string, story: unknown): void { this._stories.set(key, story); } get(key: string): unknown { return this._stories.get(key); } count(): number { return this._stories.size; } }
export class ShortStoryValidator { validate(story: { words: number; themes: string[] }): { valid: boolean; issues: string[] } { const issues: string[] = []; if (story.words < 100) issues.push('too short'); if (story.themes.length === 0) issues.push('no theme'); return { valid: issues.length === 0, issues }; } isValid(r: { valid: boolean }): boolean { return r.valid; } }
export class ShortStoryTools { tools: string[] = ['Scrivener', 'Google Docs', 'Notion']; isAvailable(t: string): boolean { return this.tools.includes(t); } count(): number { return this.tools.length; } }
export class ShortStoryMarketCheck { check(story: { genre: string; words: number }): { viable: boolean; market: string } { return { viable: story.words >= 1000, market: story.genre }; } isViable(r: { viable: boolean }): boolean { return r.viable; } }
export class ShortStoryCompensation { compute(story: { words: number; ratePerWord: number }): number { return story.words * story.ratePerWord; } isPaid(amount: number, threshold = 100): boolean { return amount >= threshold; } }
export class ShortStoryADirector2 { decide(state: { drafted: boolean; reviewed: boolean }): string { if (!state.drafted) return 'draft'; if (!state.reviewed) return 'review'; return 'submit'; } }
export class ShortStoryMasterIndex { list(): string[] { return ['StoryCondenser', 'ThemeExtracter', 'PlotCompressor', 'CharacterReducer', 'ScenePacker', 'WordBudgetEnforcer', 'ImpactMaximizer', 'ShortStoryHook', 'ShortStoryPacing', 'ShortStoryStructure', 'ShortStoryGenreAdapter', 'ShortStoryLengthChecker', 'ShortStoryConflictFocuser', 'ShortStoryTwistBuilder', 'ShortStoryToneSelector', 'ShortStoryProtagonistSelector', 'ShortStoryWordplayInserter', 'ShortStoryEndingPolisher', 'ShortStoryPipeline', 'ShortStoryDirector', 'ShortStoryReport', 'ShortStoryLibrary', 'ShortStoryValidator', 'ShortStoryTools', 'ShortStoryMarketCheck', 'ShortStoryCompensation', 'ShortStoryADirector2', 'ShortStoryMasterIndex']; } count(): number { return this.list().length; } }
export const BH_BATCH_3_ENGINES = { ShortStoryPipeline, ShortStoryDirector, ShortStoryReport, ShortStoryLibrary, ShortStoryValidator, ShortStoryTools, ShortStoryMarketCheck, ShortStoryCompensation, ShortStoryADirector2, ShortStoryMasterIndex } as const;