/**
 * IntensityCore.ts — Direction AW, V3766-V3775 (Batch 1/3)
 * Emotion Intensity Tuner: 情绪强度调节核心
 */

export class EmotionIntensityScorer { score(text: string): number { let s = 0; if (/[！!]/.test(text)) s += 0.3; if (/[？?]/.test(text)) s += 0.2; if (/[。.]/.test(text)) s += 0.1; if (text.length > 100) s += 0.2; return Math.min(1, s); } isHigh(score: number, threshold = 0.7): boolean { return score >= threshold; } }
export class IntensityAdjuster { amplify(text: string, factor: number): string { const factor2 = Math.max(1, factor); return text + '！'.repeat(Math.round(factor2 * 3)); } dampen(text: string): string { return text.replace(/！/g, '.').replace(/!/g, '.'); } }
export class EmotionPeakDetector { detect(text: string): { position: number; intensity: number } { const m = text.match(/[！!]/g); const pos = text.indexOf('！') >= 0 ? text.indexOf('！') : text.indexOf('!'); return { position: pos, intensity: (m || []).length / Math.max(1, text.length / 10) }; } hasPeak(text: string): boolean { return this.detect(text).intensity > 0; } }
export class IntensityCalibrator { calibrate(target: number, actual: number): number { return Math.max(0, target - actual); } isCalibrated(difference: number, threshold = 0.1): boolean { return difference <= threshold; } }
export class EmotionDynamics { arc(emotions: string[]): string[] { return emotions; } isMonotone(emotions: string[]): boolean { return emotions.every((e) => e === emotions[0]); } isVaried(emotions: string[]): boolean { return new Set(emotions).size > 1; } }
export class EmotionCurveSmoother { smooth(curve: number[]): number[] { return curve.map((v, i) => i === 0 ? v : Math.max(0, Math.min(1, (v + curve[i - 1]) / 2))); } isSmoother(smoothed: number[]): boolean { for (let i = 1; i < smoothed.length; i++) { if (Math.abs(smoothed[i] - smoothed[i - 1]) > 0.3) return false; } return true; } }
export class MoodTransitioner { transition(from: string, to: string): string { const transitions: Record<string, string> = { joy: 'sadness', sadness: 'anger', anger: 'joy' }; return transitions[from] === to ? 'natural' : 'forced'; } isNatural(from: string, to: string): boolean { return this.transition(from, to) === 'natural'; } }
export class EmotionIntensityTuner { tune(text: string, target: number): string { const current = new EmotionIntensityScorer().score(text); if (current < target) return text + '！'.repeat(Math.round((target - current) * 5)); return new IntensityAdjuster().dampen(text); } isTuned(text: string, target: number): boolean { return Math.abs(new EmotionIntensityScorer().score(text) - target) < 0.5; } }
export class EmotionBalance { balance(emotions: Record<string, number>): { positive: number; negative: number; ratio: number } { const pos = (emotions.joy || 0) + (emotions.hope || 0); const neg = (emotions.sadness || 0) + (emotions.fear || 0); return { positive: pos, negative: neg, ratio: neg === 0 ? pos : pos / neg }; } isBalanced(b: { positive: number; negative: number }): boolean { return b.positive > 0 && b.negative > 0; } }
export class IntensityCoreIndex { list(): string[] { return ['EmotionIntensityScorer', 'IntensityAdjuster', 'EmotionPeakDetector', 'IntensityCalibrator', 'EmotionDynamics', 'EmotionCurveSmoother', 'MoodTransitioner', 'EmotionIntensityTuner', 'EmotionBalance']; } count(): number { return this.list().length; } }
export const AW_BATCH_1_ENGINES = { EmotionIntensityScorer, IntensityAdjuster, EmotionPeakDetector, IntensityCalibrator, EmotionDynamics, EmotionCurveSmoother, MoodTransitioner, EmotionIntensityTuner, EmotionBalance, IntensityCoreIndex } as const;