/**
 * MultiPlatformCore.ts — Direction BY, V4526-V4535 (Batch 1/3)
 * Multi-Platform Publisher: 多平台发布核心
 */

export class PlatformAccountManager { private _accounts = new Map<string, { platform: string; token: string }>(); add(platform: string, token: string): void { this._accounts.set(platform, { platform, token }); } get(platform: string): { platform: string; token: string } | null { return this._accounts.get(platform) || null; } isConnected(platform: string): boolean { return this._accounts.has(platform); } count(): number { return this._accounts.size; } }
export class PlatformSelector { platforms: string[] = ['tomato', 'qidian', 'qq', 'wechat', 'zongheng']; select(book: { genre: string }): string { if (book.genre === 'romance') return 'qidian'; return 'tomato'; } isValid(p: string): boolean { return this.platforms.includes(p); } }
export class UnifiedContentAdapter { adapt(content: { title: string; content: string; chapters: string[] }, platform: string): { title: string; content: string; chapters: string[]; platform: string } { return { ...content, platform }; } isAdapted(c: { platform: string }): boolean { return c.platform.length > 0; } }
export class PlatformValidator { validate(content: { title: string; content: string }, platform: string): { valid: boolean } { return { valid: content.title.length > 0 && content.content.length > 0 && platform.length > 0 }; } isValid(r: { valid: boolean }): boolean { return r.valid; } }
export class ConcurrentUploader { upload(platforms: string[], content: { title: string }): { platform: string; status: string }[] { return platforms.map((p) => ({ platform: p, status: 'uploaded' })); } isUploaded(r: { status: string }[]): boolean { return r.every((x) => x.status === 'uploaded'); } }
export class PlatformSyncStatus { status = new Map<string, string>(); set(platform: string, status: string): void { this.status.set(platform, status); } get(platform: string): string | undefined { return this.status.get(platform); } isSynced(platform: string): boolean { return this.status.get(platform) === 'synced'; } }
export class PlatformMetadataConverter { convert(meta: { title: string; tags: string[] }, platform: string): { title: string; tags: string[]; platform: string } { return { ...meta, platform }; } isConverted(m: { platform: string }): boolean { return m.platform.length > 0; } }
export class PlatformCoverAdapter { adapt(cover: { url: string }, platform: string): { url: string; platform: string; size: { width: number; height: number } } { const sizes: Record<string, { width: number; height: number }> = { tomato: { width: 600, height: 800 }, qidian: { width: 800, height: 1000 } }; return { url: cover.url, platform, size: sizes[platform] || { width: 500, height: 700 } }; } isAdapted(c: { size: { width: number } }): boolean { return c.size.width > 0; } }
export class PlatformRetryManager { attempts = new Map<string, number>(); record(platform: string): number { const n = (this.attempts.get(platform) || 0) + 1; this.attempts.set(platform, n); return n; } shouldRetry(platform: string, max: number = 3): boolean { return (this.attempts.get(platform) || 0) < max; } }
export class PlatformBatchScheduler { schedule: { platform: string; time: string }[] = []; add(platform: string, time: string): void { this.schedule.push({ platform, time }); } isValid(): boolean { return this.schedule.length > 0; } count(): number { return this.schedule.length; } }
export class MultiPlatformCoreIndex { list(): string[] { return ['PlatformAccountManager', 'PlatformSelector', 'UnifiedContentAdapter', 'PlatformValidator', 'ConcurrentUploader', 'PlatformSyncStatus', 'PlatformMetadataConverter', 'PlatformCoverAdapter', 'PlatformRetryManager', 'PlatformBatchScheduler']; } count(): number { return this.list().length; } }
export const BY_BATCH_1_ENGINES = { PlatformAccountManager, PlatformSelector, UnifiedContentAdapter, PlatformValidator, ConcurrentUploader, PlatformSyncStatus, PlatformMetadataConverter, PlatformCoverAdapter, PlatformRetryManager, PlatformBatchScheduler, MultiPlatformCoreIndex } as const;