/**
 * TMEngineIntegration.ts — Direction BC, V3966-V3975 (Batch 3/3 收口)
 * Translation Memory Engine: 集成 + 收口
 */

import { TMEntry, TMStore } from './TMEngineCore';

export class TMEngine { private _store = new TMStore(); getStore(): TMStore { return this._store; } importTM(json: string): void { const entries = JSON.parse(json) as TMEntry[]; for (const e of entries) this._store.add(e); } exportTM(): string { return JSON.stringify(this._store.getAll()); } lookup(source: string): string { return this._store.find(source)?.target || source; } size(): number { return this._store.size(); } }
export class TMEngineMetrics { totalQueries = 0; exactMatches = 0; fuzzyMatches = 0; recordQuery(exact: boolean): void { this.totalQueries += 1; if (exact) this.exactMatches += 1; else this.fuzzyMatches += 1; } exactMatchRate(): number { return this.totalQueries === 0 ? 0 : this.exactMatches / this.totalQueries; } }
export class TMEngineConfig { maxEntries = 1000; minQuality = 0.5; isValid(config: { maxEntries: number; minQuality: number }): boolean { return config.maxEntries > 0 && config.minQuality >= 0 && config.minQuality <= 1; } }
export class TMEngineSync { local: TMStore = new TMStore(); remote: TMStore = new TMStore(); sync(): { added: number; updated: number } { let added = 0; let updated = 0; for (const e of this.remote.getAll()) { const local = this.local.find(e.source); if (!local) { this.local.add(e); added += 1; } else if (local.target !== e.target) { local.target = e.target; updated += 1; } } return { added, updated }; } }
export class TMEngineAudit { audit(store: TMStore): { lowQuality: number; duplicates: number } { const entries = store.getAll(); const lowQuality = entries.filter((e) => e.quality < 0.5).length; const sources = entries.map((e) => e.source); const duplicates = sources.length - new Set(sources).size; return { lowQuality, duplicates }; } isHealthy(a: { lowQuality: number; duplicates: number }): boolean { return a.lowQuality === 0 && a.duplicates === 0; } }
export class TMEngineLibrary { private _stores = new Map<string, TMStore>(); save(key: string, store: TMStore): void { this._stores.set(key, store); } get(key: string): TMStore | null { return this._stores.get(key) || null; } count(): number { return this._stores.size; } }
export class TMEngineADirector { decide(state: { queryCount: number; cacheHitRate: number }): string { if (state.queryCount === 0) return 'seed'; if (state.cacheHitRate < 0.5) return 'expand'; return 'maintain'; } }
export class TMEngineTools { tools: string[] = ['Trados', 'MemoQ', 'OmegaT', 'Smartcat']; isAvailable(t: string): boolean { return this.tools.includes(t); } count(): number { return this.tools.length; } }
export class TMEngineExportFormat { exportTMX(store: TMStore): string { return `<?xml version="1.0"?><tmx>${store.getAll().map((e) => `<tu><tuv><seg>${e.source}</seg></tuv><tuv><seg>${e.target}</seg></tuv></tu>`).join('')}</tmx>`; } isValid(s: string): boolean { return s.startsWith('<?xml'); } }
export class TMEngineMasterIndex { list(): string[] { return ['TMStore', 'TMIndexer', 'TMQuery', 'TMSegmenter', 'TMAlignment', 'TMQuality', 'TMContext', 'TMUpdate', 'TMExport', 'TMImport', 'TMConcordancer', 'TMConvergence', 'TMPretranslation', 'TMLeverage', 'TMConsistency', 'TMStatistics', 'TMEditor', 'TMVersioning', 'TMBatch', 'TMEngine', 'TMEngineMetrics', 'TMEngineConfig', 'TMEngineSync', 'TMEngineAudit', 'TMEngineLibrary', 'TMEngineADirector', 'TMEngineTools', 'TMEngineExportFormat', 'TMEngineMasterIndex']; } count(): number { return this.list().length; } }
export const BC_BATCH_3_ENGINES = { TMEngine, TMEngineMetrics, TMEngineConfig, TMEngineSync, TMEngineAudit, TMEngineLibrary, TMEngineADirector, TMEngineTools, TMEngineExportFormat, TMEngineMasterIndex } as const;