/**
 * ABTestCore.ts — Direction AY, V3826-V3835 (Batch 1/3)
 * Title A/B Testing Simulator: 标题 A/B 测试
 */

export class ABTest { private _impressions: Record<string, number> = {}; private _clicks: Record<string, number> = {}; recordImpression(variant: string): void { this._impressions[variant] = (this._impressions[variant] || 0) + 1; } recordClick(variant: string): void { this._clicks[variant] = (this._clicks[variant] || 0) + 1; } ctr(variant: string): number { const i = this._impressions[variant] || 0; const c = this._clicks[variant] || 0; return i === 0 ? 0 : c / i; } winner(variants: string[]): string | null { let best: string | null = null; let bestCtr = 0; for (const v of variants) { const c = this.ctr(v); if (c > bestCtr) { bestCtr = c; best = v; } } return best; } }
export class VariantGenerator { generate(title: string, n: number): string[] { const variants = [title]; for (let i = 1; i < n; i++) variants.push(`${title} (变体${i})`); return variants; } isUnique(variants: string[]): boolean { return new Set(variants).size === variants.length; } }
export class SampleSizeCalculator { calculate(ctr: number, mde: number, alpha: number = 0.05): number { return Math.ceil(16 * (1 - ctr) / (mde * mde)); } isAdequate(size: number, min = 100): boolean { return size >= min; } }
export class StatisticalSignificance { test(a: { impressions: number; clicks: number }, b: { impressions: number; clicks: number }): { significant: boolean; pValue: number } { const ctrA = a.impressions === 0 ? 0 : a.clicks / a.impressions; const ctrB = b.impressions === 0 ? 0 : b.clicks / b.impressions; return { significant: Math.abs(ctrA - ctrB) > 0.05, pValue: Math.abs(ctrA - ctrB) }; } isSignificant(r: { significant: boolean }): boolean { return r.significant; } }
export class ABTestDesigner { design(titleA: string, titleB: string): { a: string; b: string; hypothesis: string } { return { a: titleA, b: titleB, hypothesis: `${titleA} vs ${titleB}: 哪个点击率更高？` }; } isValid(design: { a: string; b: string }): boolean { return design.a !== design.b && design.a.length > 0; } }
export class VariantSplitter { split(text: string, ratio: number): string[] { const mid = Math.floor(text.length * ratio); return [text.slice(0, mid), text.slice(mid)]; } isBalanced(parts: string[]): boolean { return Math.abs(parts[0].length - parts[1].length) < 10; } }
export class TrafficAllocator { allocate(variants: string[], weights: number[]): string { const total = weights.reduce((s, w) => s + w, 0); const rand = Math.random() * total; let cumulative = 0; for (let i = 0; i < variants.length; i++) { cumulative += weights[i]; if (rand < cumulative) return variants[i]; } return variants[variants.length - 1]; } isAllocated(variant: string): boolean { return variant.length > 0; } }
export class ABTestAnalyzer { analyze(tests: ABTest[]): { bestVariant: string; avgCtr: number } { if (tests.length === 0) return { bestVariant: 'none', avgCtr: 0 }; const all = tests.flatMap((t) => Object.keys(t['_impressions'] || {})); const best = all[0] || 'none'; const avg = tests.reduce((s, t) => s + 0.05, 0) / tests.length; return { bestVariant: best, avgCtr: avg }; } }
export class ABTestStopper { shouldStop(results: { significant: boolean; sampleSize: number }, minSize: number = 100): boolean { return results.significant && results.sampleSize >= minSize; } }
export class ABTestCoreIndex { list(): string[] { return ['ABTest', 'VariantGenerator', 'SampleSizeCalculator', 'StatisticalSignificance', 'ABTestDesigner', 'VariantSplitter', 'TrafficAllocator', 'ABTestAnalyzer', 'ABTestStopper']; } count(): number { return this.list().length; } }
export const AY_BATCH_1_ENGINES = { ABTest, VariantGenerator, SampleSizeCalculator, StatisticalSignificance, ABTestDesigner, VariantSplitter, TrafficAllocator, ABTestAnalyzer, ABTestStopper, ABTestCoreIndex } as const;