/**
 * SprintIntegration.ts — Direction BD, V3996-V4005 (Batch 3/3 收口)
 * Writing Sprint Timer: 集成 + 收口
 */

export class SprintRunner { private _sprints: { date: string; words: number; duration: number }[] = []; run(date: string, words: number, duration: number): void { this._sprints.push({ date, words, duration }); } averageWpm(): number { if (this._sprints.length === 0) return 0; return this._sprints.reduce((s, sp) => s + sp.words / sp.duration, 0) / this._sprints.length; } totalWords(): number { return this._sprints.reduce((s, sp) => s + sp.words, 0); } }
export class SprintSchedule { schedule: { day: string; sprint: number }[] = []; add(day: string, sprint: number): void { this.schedule.push({ day, sprint }); } hasOnDay(day: string): boolean { return this.schedule.some((s) => s.day === day); } }
export class SprintChallenge { goal: number = 0; set(goal: number): void { this.goal = goal; } isCompleted(progress: number): boolean { return progress >= this.goal; } }
export class SprintPhase { phase: 'warmup' | 'peak' | 'cooldown' = 'warmup'; duration(phase: string): number { return phase === 'warmup' ? 5 : phase === 'peak' ? 60 : 5; } isValid(phase: string): boolean { return ['warmup', 'peak', 'cooldown'].includes(phase); } }
export class SprintFocusMusic { genre: string = 'lofi'; isCalming(g: string): boolean { return g === 'lofi' || g === 'classical'; } isEnergizing(g: string): boolean { return g === 'electronic' || g === 'rock'; } }
export class SprintADirector { decide(state: { lastSprintWords: number; goal: number }): string { if (state.lastSprintWords === 0) return 'start'; if (state.lastSprintWords >= state.goal) return 'continue'; return 'rest'; } }
export class SprintLibrary { private _templates: { name: string; duration: number; words: number }[] = []; add(name: string, duration: number, words: number): void { this._templates.push({ name, duration, words }); } findByWords(target: number): { name: string; duration: number; words: number } | null { return this._templates.find((t) => t.words === target) || null; } count(): number { return this._templates.length; } }
export class SprintTools { tools: string[] = ['Pomodoro', 'Flowtime', '52/17']; isAvailable(t: string): boolean { return this.tools.includes(t); } count(): number { return this.tools.length; } }
export class SprintReport { generate(runs: { words: number; duration: number }[]): string { const total = runs.reduce((s, r) => s + r.words, 0); return `共 ${runs.length} 次冲刺, 总字数 ${total}`; } hasReport(s: string): boolean { return s.includes('冲刺'); } }
export class SprintMasterIndex { list(): string[] { return ['SprintTimer', 'SprintTracker', 'SprintSessionType', 'SprintProgress', 'SprintGoalSetter', 'SprintBreakTimer', 'SprintGoalPredictor', 'SprintDistractionLogger', 'SprintStats', 'SprintLeaderboard', 'SprintGroupSession', 'SprintReward', 'SprintStreak', 'SprintNotification', 'SprintRecoveryTime', 'SprintEnergyEstimate', 'SprintProductivityCalculator', 'SprintHabit', 'SprintRunner', 'SprintSchedule', 'SprintChallenge', 'SprintPhase', 'SprintFocusMusic', 'SprintADirector', 'SprintLibrary', 'SprintTools', 'SprintReport', 'SprintMasterIndex']; } count(): number { return this.list().length; } }
export const BD_BATCH_3_ENGINES = { SprintRunner, SprintSchedule, SprintChallenge, SprintPhase, SprintFocusMusic, SprintADirector, SprintLibrary, SprintTools, SprintReport, SprintMasterIndex } as const;