/**
 * SprintCore.ts — Direction BD, V3976-V3985 (Batch 1/3)
 * Writing Sprint Timer: 写作冲刺核心
 */

export class SprintTimer { start(durationMinutes: number): { startTime: number; duration: number } { return { startTime: Date.now(), duration: durationMinutes }; } isComplete(sprint: { startTime: number; duration: number }): boolean { return (Date.now() - sprint.startTime) / 60000 >= sprint.duration; } remaining(sprint: { startTime: number; duration: number }): number { return Math.max(0, sprint.duration - (Date.now() - sprint.startTime) / 60000); } }
export class SprintTracker { private _sprints: { startTime: number; duration: number; words: number }[] = []; record(sprint: { startTime: number; duration: number }, words: number): void { this._sprints.push({ ...sprint, words }); } totalWords(): number { return this._sprints.reduce((s, sp) => s + sp.words, 0); } sprintCount(): number { return this._sprints.length; } }
export class SprintSessionType { type: 'pomodoro' | 'flow' | 'free' = 'free'; isStructured(): boolean { return this.type !== 'free'; } getDuration(): number { const map: Record<string, number> = { pomodoro: 25, flow: 90, free: 30 }; return map[this.type]; } }
export class SprintProgress { progress(sprint: { duration: number; startTime: number }): number { const elapsed = (Date.now() - sprint.startTime) / 60000; return Math.min(1, elapsed / sprint.duration); } isHalfway(sprint: { duration: number; startTime: number }): boolean { return this.progress(sprint) >= 0.5; } }
export class SprintGoalSetter { goal: number = 0; set(goal: number): void { this.goal = goal; } isAchieved(wordsWritten: number): boolean { return wordsWritten >= this.goal; } progress(wordsWritten: number): number { return this.goal === 0 ? 0 : wordsWritten / this.goal; } }
export class SprintBreakTimer { startBreak(durationMinutes: number = 5): { startTime: number; duration: number } { return { startTime: Date.now(), duration: durationMinutes }; } isOver(breakTime: { startTime: number; duration: number }): boolean { return (Date.now() - breakTime.startTime) / 60000 >= breakTime.duration; } }
export class SprintGoalPredictor { predict(currentWords: number, elapsedMinutes: number, totalMinutes: number): number { const rate = currentWords / Math.max(1, elapsedMinutes); return Math.round(rate * totalMinutes); } isOnTrack(predict: number, goal: number): boolean { return predict >= goal; } }
export class SprintDistractionLogger { private _distractions: { time: number; type: string }[] = []; log(type: string): void { this._distractions.push({ time: Date.now(), type }); } count(): number { return this._distractions.length; } }
export class SprintStats { private _totalWords = 0; private _totalMinutes = 0; record(words: number, minutes: number): void { this._totalWords += words; this._totalMinutes += minutes; } wpm(): number { return this._totalMinutes === 0 ? 0 : this._totalWords / this._totalMinutes; } totalWords(): number { return this._totalWords; } }
export class SprintCoreIndex { list(): string[] { return ['SprintTimer', 'SprintTracker', 'SprintSessionType', 'SprintProgress', 'SprintGoalSetter', 'SprintBreakTimer', 'SprintGoalPredictor', 'SprintDistractionLogger', 'SprintStats']; } count(): number { return this.list().length; } }
export const BD_BATCH_1_ENGINES = { SprintTimer, SprintTracker, SprintSessionType, SprintProgress, SprintGoalSetter, SprintBreakTimer, SprintGoalPredictor, SprintDistractionLogger, SprintStats, SprintCoreIndex } as const;