/**
 * BetaReaderMatchIntegration.ts — Direction BF, V4056-V4065 (Batch 3/3 收口)
 * Beta Reader Auto-Match: 集成 + 收口
 */

export class MatchPipeline { steps: string[] = ['build', 'match', 'rank', 'contact', 'feedback']; isComplete(step: string): boolean { return this.steps[this.steps.length - 1] === step; } next(step: string): string { const i = this.steps.indexOf(step); return i >= 0 && i < this.steps.length - 1 ? this.steps[i + 1] : 'done'; } }
export class MatchADirector2 { decide(state: { bookReady: boolean; matchCount: number }): string { if (!state.bookReady) return 'wait'; if (state.matchCount < 3) return 'find_more'; return 'send_invites'; } }
export class MatchNotification { send(reader: string, message: string): void {} hasNotified(m: string): boolean { return m.length > 0; } }
export class MatchTracker { private _matches: { reader: string; date: string; score: number }[] = []; record(reader: string, score: number): void { this._matches.push({ reader, date: new Date().toISOString(), score }); } count(): number { return this._matches.length; } }
export class MatchValidator { validate(match: { reader: string; score: number }): { valid: boolean; issues: string[] } { const issues: string[] = []; if (!match.reader) issues.push('no reader'); if (match.score < 0) issues.push('invalid score'); return { valid: issues.length === 0, issues }; } isValid(r: { valid: boolean }): boolean { return r.valid; } }
export class MatchDashboard { generate(stats: { total: number; matched: number }): string { return `总 ${stats.total} 读者, 已匹配 ${stats.matched}`; } hasDashboard(s: string): boolean { return s.includes('匹配'); } }
export class MatchLibrary { private _matches = new Map<string, unknown>(); save(key: string, data: unknown): void { this._matches.set(key, data); } get(key: string): unknown { return this._matches.get(key); } count(): number { return this._matches.size; } }
export class MatchTools { tools: string[] = ['Email', 'Slack', 'Discord', 'Forum']; isAvailable(t: string): boolean { return this.tools.includes(t); } count(): number { return this.tools.length; } }
export class MatchReportGenerator { generate(stats: { readers: number; invited: number; accepted: number }): string { return `${stats.readers} 读者, ${stats.invited} 邀请, ${stats.accepted} 接受`; } hasReport(s: string): boolean { return s.includes('邀请'); } }
export class BetaReaderMatchMasterIndex { list(): string[] { return ['ReaderProfileBuilder', 'PreferenceMatcher', 'DemographicsMatcher', 'ReaderRanker', 'ReaderDatabase', 'MatchScoreCalculator', 'MatchThreshold', 'MatchReport', 'MatchADirector', 'ReaderAvailability', 'ReaderSpecialization', 'ReaderRating', 'ReaderFeedbackCollector', 'ReaderMatchingEngine', 'ReaderDiversityCalculator', 'ReaderRecruitment', 'ReaderRetentionPredictor', 'ReaderOnboarding', 'MatchPipeline', 'MatchADirector2', 'MatchNotification', 'MatchTracker', 'MatchValidator', 'MatchDashboard', 'MatchLibrary', 'MatchTools', 'MatchReportGenerator', 'BetaReaderMatchMasterIndex']; } count(): number { return this.list().length; } }
export const BF_BATCH_3_ENGINES = { MatchPipeline, MatchADirector2, MatchNotification, MatchTracker, MatchValidator, MatchDashboard, MatchLibrary, MatchTools, MatchReportGenerator, BetaReaderMatchMasterIndex } as const;