/**
 * BackmatterIndexerAdvanced.ts — Direction BB, V3926-V3935 (Batch 2/3)
 * Backmatter Indexer: 高级工具
 */

export class BackmatterExporter { exportToMarkdown(items: { title: string; content: string }[]): string { return items.map((i) => `# ${i.title}\n\n${i.content}`).join('\n\n---\n\n'); } isValid(s: string): boolean { return s.includes('#'); } }
export class BackmatterImporter { importFromMarkdown(md: string): { title: string; content: string }[] { const parts = md.split(/^# /m).filter((p) => p.trim()); return parts.map((p) => { const lines = p.split('\n'); return { title: lines[0], content: lines.slice(1).join('\n').trim() }; }); } isValid(s: string): boolean { return s.includes('#'); } }
export class BackmatterIndexExporter { exportJSON(index: { allCategories: () => string[]; get: (c: string) => string[] }): string { return JSON.stringify({ categories: index.allCategories(), items: index.allCategories().reduce((acc, c) => ({ ...acc, [c]: index.get(c) }), {}) }); } isValidJSON(s: string): boolean { return s.startsWith('{'); } }
export class BackmatterSearchEngine { search(items: { content: string; tags: string[] }[], query: string): { item: any; score: number }[] { return items.filter((i) => i.content.includes(query) || i.tags.includes(query)).map((i) => ({ item: i, score: 1 })); } isRanked(r: { score: number }[]): boolean { return r.every((x, i) => i === 0 || x.score <= r[i - 1].score); } }
export class BackmatterArchive { private _archive: { year: number; count: number }[] = []; record(year: number, count: number): void { this._archive.push({ year, count }); } totalCount(): number { return this._archive.reduce((s, a) => s + a.count, 0); } }
export class BackmatterReferenceGraph { private _graph = new Map<string, string[]>(); addEdge(from: string, to: string): void { if (!this._graph.has(from)) this._graph.set(from, []); this._graph.get(from)!.push(to); } getRelated(node: string): string[] { return this._graph.get(node) || []; } isConnected(from: string, to: string): boolean { const visited = new Set<string>([from]); const queue = [from]; while (queue.length > 0) { const current = queue.shift()!; if (current === to) return true; for (const n of this._graph.get(current) || []) { if (!visited.has(n)) { visited.add(n); queue.push(n); } } } return false; } }
export class BackmatterCatalog { private _catalog: { title: string; type: string; page: number }[] = []; add(title: string, type: string, page: number): void { this._catalog.push({ title, type, page }); } byType(type: string): { title: string; type: string; page: number }[] { return this._catalog.filter((c) => c.type === type); } count(): number { return this._catalog.length; } }
export class BackmatterValidator { validate(item: { title: string; content: string }): { valid: boolean; issues: string[] } { const issues: string[] = []; if (item.title.length < 3) issues.push('title too short'); if (item.content.length < 10) issues.push('content too short'); return { valid: issues.length === 0, issues }; } isValid(r: { valid: boolean }): boolean { return r.valid; } }
export class BackmatterAdvancedIndex { list(): string[] { return ['BackmatterExporter', 'BackmatterImporter', 'BackmatterIndexExporter', 'BackmatterSearchEngine', 'BackmatterArchive', 'BackmatterReferenceGraph', 'BackmatterCatalog', 'BackmatterValidator']; } count(): number { return this.list().length; } }
export const BB_BATCH_2_ENGINES = { BackmatterExporter, BackmatterImporter, BackmatterIndexExporter, BackmatterSearchEngine, BackmatterArchive, BackmatterReferenceGraph, BackmatterCatalog, BackmatterValidator, BackmatterAdvancedIndex } as const;