/**
 * RatingAggregatorCore.ts — Direction BN, V4276-V4285 (Batch 1/3)
 * Beta Reader Rating Aggregator: 评分聚合
 */

export class RatingCollector { private _ratings: { reader: string; rating: number; category: string }[] = []; collect(reader: string, rating: number, category: string): void { this._ratings.push({ reader, rating, category }); } getAll(): { reader: string; rating: number; category: string }[] { return [...this._ratings]; } count(): number { return this._ratings.length; } }
export class RatingAverage { average(ratings: number[]): number { if (ratings.length === 0) return 0; return ratings.reduce((s, r) => s + r, 0) / ratings.length; } isPositive(a: number, threshold = 3): boolean { return a >= threshold; } }
export class RatingMedian { median(ratings: number[]): number { if (ratings.length === 0) return 0; const sorted = [...ratings].sort((a, b) => a - b); const mid = Math.floor(sorted.length / 2); return sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid]; } isValid(m: number): boolean { return !isNaN(m); } }
export class RatingDistribution { distribution(ratings: number[]): Map<number, number> { const map = new Map<number, number>(); for (const r of ratings) map.set(r, (map.get(r) || 0) + 1); return map; } hasSpread(d: Map<number, number>): boolean { return d.size >= 2; } }
export class RatingConsensus { consensus(ratings: { rating: number }[]): number { if (ratings.length === 0) return 0; const avg = ratings.reduce((s, r) => s + r.rating, 0) / ratings.length; const variance = ratings.reduce((s, r) => s + Math.pow(r.rating - avg, 2), 0) / ratings.length; return 1 - Math.min(1, variance); } isConsensus(c: number, threshold = 0.5): boolean { return c >= threshold; } }
export class RatingOutlier { detect(ratings: number[]): number | null { if (ratings.length === 0) return null; const avg = ratings.reduce((s, r) => s + r, 0) / ratings.length; const max = Math.max(...ratings); const min = Math.min(...ratings); return Math.abs(max - avg) > Math.abs(avg - min) ? max : min; } hasOutlier(ratings: number[]): boolean { return this.detect(ratings) !== null; } }
export class RatingSummary { summarize(stats: { avg: number; count: number }): string { return `平均 ${stats.avg.toFixed(1)} (${stats.count} 评)`; } hasSummary(s: string): boolean { return s.includes('平均'); } }
export class RatingReport { generate(ratings: { reader: string; rating: number }[]): string { return ratings.map((r) => `${r.reader}: ${r.rating}`).join(', '); } isValid(s: string): boolean { return s.includes(':'); } }
export class RatingTrend { history: number[] = []; record(r: number): void { this.history.push(r); } trend(): 'up' | 'down' | 'stable' { if (this.history.length < 2) return 'stable'; const recent = this.history[this.history.length - 1]; const previous = this.history[this.history.length - 2]; return recent > previous ? 'up' : recent < previous ? 'down' : 'stable'; } }
export class RatingAggregatorCoreIndex { list(): string[] { return ['RatingCollector', 'RatingAverage', 'RatingMedian', 'RatingDistribution', 'RatingConsensus', 'RatingOutlier', 'RatingSummary', 'RatingReport', 'RatingTrend']; } count(): number { return this.list().length; } }
export const BN_BATCH_1_ENGINES = { RatingCollector, RatingAverage, RatingMedian, RatingDistribution, RatingConsensus, RatingOutlier, RatingSummary, RatingReport, RatingTrend, RatingAggregatorCoreIndex } as const;